package com.gery.statsapp;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.Window;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.ListView;

public class GlossaryActivity extends Activity
{

	private ListView listView;
	ArrayAdapter<String> adapter;
	String [] definitions = {"2x2 table","Agreement","ANOVA","Association","Average","Binary","Categorical","Categorical data assumptions","Censored observations","Chance","Chance agreement","Chi squared test","Confounding","Contingency table","Descriptive statistics","Disagreement","Distribution","Expected values","Extreme proportions","Factorial ANOVA","Frequencies (numeric counts)","Graphical display","Grouping variables","Groups","Hypothesised","Independent","Independent groups","Interactions","Inter-rater","Levels","MANOVA","Mean","Median","Model Fit","Multinomial","Nominal","Nonparametric","Numeric","Observed data","One-to-one matched","One-way ANOVA","Ordinal","Outcome","Outliers (outlying values)","Paired","Paired t-test","Parametric data assumptions","Percentage","Predictor variable","Proportion","Rank","Rater","Regression","Regression model","Reliability","Repeatability","Repeated measurements","Residuals","Sample(s)","Significance test","Significant","Spread","Study design","Table cells","Test-retest","Time-to-event","Total agreement","t-test (One-sample)","t-test (Two-samples)","Variability","Variable(s)","Weighted",""};
	String [] data = {
					"A 2x2 table represents the outcomes of two binary categorical variables; the table has four data cells representing the four possible outcomes of the two variables. Often the 2x2 table is also presented with marginal totals.e.g. A 2x2 table of gender and smoking status in 100 people. 2x2 tables (and extensions of the 2x2 to k x k) are used in Chi Squared analyses of difference/association between two categorical variables, and in Kappa analyses of agreement between two categorical measurements.",
					"Agreement means to give the same response. In statistical analyses agreement refers to similarity in rating by two or more raters, or across two or more ratings. It may also be referred to as measurement of reliability or repeatability. Complete or absolute agreement means that raters or ratings are identical on all occasions",
					"ANOVA stands for Analysis of Variance: this group of tests is used to assess associations between grouping variables and numeric outcomes, by comparing mean outcomes scores between three or more groups. ANOVA can analyse multiple grouping variables (e.g. Gender, condition, favourite colour), each with multiple categories/levels (e.g. Male and female, placebo, new drug, old drug, and control, red, blue, green, yellow, etc.), and multiple numeric outcomes (e.g. Height, weight, blood pressure).",
					"Association is another word for relationship or link." +
					"\n\nIt is common to describe the relationship between two numeric variables as an association. For example, if ice cream sales increased as outside temperature increases, ice cream sales are associated with outdoor temperature." +
					"\n\nAssociation is also used to describe observed relationships between a numeric variable and a categorical/grouping variable (e.g. Height and gender), or between two categorical variables (e.g. Smoking status and heart disease diagnosis). For example, if a difference in height is observed between men and women, we say that height difference is associated with gender.",
					"The average is a single value that is supposed to best represent a total sample of numeric data. Averages are also known as measures of central tendency or measures of centre as they should represent the middle of the data. The most common averages are the mean (add up all values and divide by the number of values) and median (the middle ranked value in a sample of data). In certain situations the mode may also be used to represent the data; the mode is the most common value(s) in a sample of data and hence there can be more than one mode.",
					"Binary means two options (bi = two), so a binary variable/measurement has only two response/result/outcome options (e.g. Gender, smoking status, or disease diagnosis).  Binary data is also sometimes known as dichotomous data (dichotomy = split into two)",
					"Categorical means something consisting of groups or categories. Categorical variables/measurements have distinct response options (categories), for which individuals should fall into only one. For example, disease diagnosis is a categorical variable because individuals either have or do not have a disease (there is no scale or continuum). Categorical variables may have two (binary), or more than two ordered (ordinal) or unordered (nominal) response options.",
					"When carrying out statistical analyses to compare categorical variables, certain data assumptions should be met in order to validly use particular tests (Chi squared, Chi squared for trend, or McNemar). " +
					"\n\nData assumptions relate to the cells of the contingency table of data: " +
					"\n		Each cell should contain an adequate sample (>20)" +
					"\n		The proportion/percentage of the total sample should not be extreme (<10% or >90%)." +
					"\n\nIf these assumptions are not met the assumption free alternative test (Fisher's exact) should be used instead." +
					"\ne.g. A 2x2 table of lung disease status and smoking status in 100 people. The data above are problematic because, although the total sample is relatively large there are two cells with small frequencies, representing very small (extreme) proportions of the overall sample.",
					"The term censored observation is relevant to survival/time-to-event analysis, and refers to a person/case who did not reach a pre-specified target event in the total time that they were followed during a study. Individuals in a survival study are followed for different lengths of time and are censored if they have not experienced the event before the study ends or they leave the study (whichever occurs first).",
					"When the word chance is used in statistical analysis it refers to a completely randomly occurring event, relationship or difference in a sample of data. The occurrence of the event, relationship or difference is not due to any experimental or systematic (logical) causes." +
					"\n\ne.g. If you split a group of 60 people into males and females and found that their heights differed on average by 8cm, some of this difference is likely to be attributed to gender differences. However, if you split the 60 people in half at random and found an average difference in height of 8cm this would be due to chance, as no systematic features were used to divide the sample.",
					"Chance agreement refers to the occasions that two measurements/raters would agree at random and not due to any specific or systematic similarities in rating or measurement." +
					"\n\nIf you repeatedly toss two fair coins, there is nothing to make the coins more or less likely to land on the same or different sides on each occasion. However, we would expect them to land on the same side approximately 50% of the time just because of random chance.",
					"The Chi Squared test assesses the association between two categorical variables. All response options for the two categorical variables are entered into a contingency table (e.g. A 2x2 table). The distribution of the sample data across the cells of the observed data table is compared to a table of expected values (the distribution of data based on chance alone, using the marginal totals from the observed data table). The degree of difference between observed and expected values, indicates whether or not a significant association exists between the two variables.",
					"In statistical analyses, confounding refers to something that can effect or influence the study results in an unplanned way. So a confounding variable is something that is not relevant to the research question but is associated with the outcome of interest and differs in terms of the groups or variables being compared, and so may affect the meaning, validity and interpretation of study results unless it is recorded and controlled for." +
					"\n\nConfounding only occurs if the factor is associated with the outcome score, and it differs between groups. Therefore, confounding can be reduced or eliminated by matching groups according to confounding factors, or by measuring confounding factors and controlling for them in the analyses." +
					"\n\ne.g. A study aims to compare the weights of children aged 5-15 from comprehensive and private schools to see if there is an association between socioeconomic status and weight status (i.e. Do the groups differ?). However, any differences observed between groups may be in part due to other confounding factors such as age and height; therefore children must either be one-to-one matched between groups for age and height, or they must be controlled for in the analyses.",
					"A contingency table is a table constructed to present the relationship between two categorical variables, to show all possible combinations of responses for each case in a sample. Often the exposure variable (grouping categories) will be entered into the rows, and the outcome variable (response categories) will be entered into the columns." +
					"\n\ne.g. A 2x2 contingency table to present the relationship between using illicit drugs and having a psychiatric disorder. The contingency table not only presents how many people in total do and do not use illicit drug, and how many do and do not have the disorder (these are called the marginal totals), but importantly the main cells of the table tells us how many people who use drugs and do not use drugs have the disorder, and how many of those who have and do not have a disorder use drugs.",
					"Descriptive statistics (also known as descriptive analyses or summary statistics) are used to summarise or describe a sample of data." +
					"\n\nFor categorical data, summaries are usually concerned with the number of people/cases falling into each study group. The numbers may be expressed as proportions (number in the group divided by the total sample size), as percentages (proportion multiplied by 100), or as odds (number in the group divided by number not in the group). " +
					"\n\ne.g. A study has 80 participants, 35 are male and the remaining 45 are female. " +
					"\n\nTo summarise the number of males in the sample: "+
						"\n	Proportion: 35 / 80 = 0.44"+
						"\n	Percentage: (35 / 80 = 0.44) x 100 = 44 percent"+
						"\n	Odds: 35 / 45 = 0.78"+
						"\nDescriptive statistics for numeric data usually include the average or centre of the data (mean, median, or sometimes the mode), and the spread of data (spread means how much each individual in the sample differs from the average value)." +
						"\n\nDifferent summaries are available for numeric data and the right one must be chosen to accurately and validly represent the whole sample of data. The most important factor in choosing and calculating appropriate descriptive statistics is the shape/distribution of the data. Producing a histogram (a bar chart with the numeric variable on the x axis and frequency on the y axis) of numeric outcome data will show whether it is normally distributed or skewed (if separate groups are to be compared, the shape of the numeric data for each group should be examined). If data are normally distributed then mean and standard deviation should be calculated to describe the data. If data are skewed then the median and interquartile range should be calculated to describe the data." +
						"\n\ne.g. Normal distribution use mean and standard deviation to summarise/describe this data. \ne.g. Skewed distribution (this example shows positive skew) use median and interquartile range to summarise/describe the data.",
					"The amount that two or more raters or repeated measurements of the same thing differ. For example if two teachers mark the same set of exam papers, the amount by which their scores for each student differ represents their level of disagreement." +
					"\n\nDisagreement may be assessed in terms of complete or absolute disagreement  (e.g. Two clinicians diagnose diabetes in a patient; one gives a positive diagnosis and the second gives a negative diagnosis), or in terms of the degree of dissimilarity in ratings that represents disagreement (e.g. Two teachers grade a student's exam paper; one teacher gives 68% and the other gives 71% - the absolute values are different but the scores are similar)",
					"Distribution refers to the shape of a sample of data. Specifically, how spread out the individual data points in the sample are from one another, and where in the total spread do the bulk or majority of points tend to lie. " +
					"\n\nThe shape of a distribution is examined by creating a histogram of the numeric variable of interest (a bar chart with the numeric variable on the x axis and frequency on the y axis). For statistical analyses, probably the most important distinction in distribution shapes is between normal distribution (e.g. 1) and skewed distribution (e.g. 2)"+
					"\n\ne.g. 1. Normal distribution: we look for approximate normality in data, so that the majority of points lie in the centre (around the mean) of the distribution and the number of people decreases as the values on the x-axis get further away from the centre."+
					"\n\ne.g. 2. Skewed distribution: the peak of the distribution is not in the centre and the tails of the shape are not symmetrical. Skewing can go in either direction and can have varying degrees of severity. ",
					"Expected values are relevant to chi squared analyses of two categorical variables, and relate to the categorical data (observed values) in a contingency table. " +
					"\n\nExpected values are based on the distribution of the data across all table cells due to chance alone; i.e. Assuming there is no association between the two categorical variables being compared. They are calculated using the table totals from the observed data." +
					"\n\ne.g. A 2x2 table of observed values for gender and smoking status in 100 people. The marginal totals show there are 54% men in the sample and 46% women, and that 26% of the sample smoke while 74% do not. These values are then used to create the expected values if division of people among the other four table cells is purely down to chance (i.e. There is no association between gender and smoking). Because the total sample is 54% male, we expect 54% of smokers (n=26) to be male and 54% of non-smokers (n=74) to be male" +
					"\n\nIn this example, the spread of participants across the four cells is very similar in the observed and expected values tables, suggesting no association between gender and smoking status.",
					"When analysing categorical data, particularly when comparing two categorical variables in a chi squared analysis (or similar), no one group/table cell should contain less than 10% or more than 90% of the data. " +
					"\n\ne.g. In the 2x2 table of lung disease status and smoking status for 100 people extreme proportions/percentages of the sample are seen in two of the four main table cells (the percentages of both smokers (5%) and non-smokers (7%) who have lung disease)",
					"Simple one-way ANOVA compares numeric outcome scores (e.g. BMI) between three or more levels of a single grouping variable (e.g. Life satisfaction: comparing between people rated as low, medium, and high)." +
					"\n\nFactorial ANOVA builds on the basic ANOVA and allows analysis of more than one grouping variable at the same time. Factorial ANOVA also assesses the interactions between the different grouping variables." +
					"\n\ne.g. A study wants to examine BMI (numeric outcome variable) in terms of gender (levels: males and females) and life satisfaction (levels: low, medium, high). The study will also examine if there is an interaction between gender and life satisfaction to explain BMI (e.g. Is the association between life satisfaction and BMI different for men and women). ",
                    "Frequency data is information recorded on a number scale (i.e. 1, 2, 3, 4k) which represents the number of discrete events or occurrences.  Numeric data tends to analysed as frequencies or counts if only whole numbers (integer values) can occur and if the range of outcome scores is small; for example, number of siblings, number of heart attacks, number of cars in your household.",
					"Graphical display refers to any table, graph, plot, picture or other display of data, which is used to summarise data instead of writing the results or describing the content into the main text of a report.",
					"A grouping variable is a categorical variable containing two or more levels, which are compared with regards to a specific outcome. Examples of grouping variables include gender, ethnicity, weight status (if categorised), smoking status, disease status, treatment group, etc." +
					"\n\nGrouping variables are also referred to as independent variables, while outcome variables may be referred to as dependent variables.",
					"Different levels or categories (e.g. Males and females, or new drug, old drug and placebo) to be compared within a grouping variable (e.g. Gender, or treatment condition).",
					"When something (i.e. An event or outcome) is hypothesised, it means it is predicted to happen. So a hypothesis is a prediction, usually based on some justification, reasoning or evidence." +
					"\n\nGenerally, two different hypotheses are used in statistical analyses; the null hypothesis that says there will be no significant difference/association, and the experimental or alternative hypothesis, which states the difference/association we expect to observe based on previous evidence or justification." +
					"\n\nIn one-sample tests (one-sample t-test or Wilcoxon sign rank test) the sample mean or median is compared to a hypothesised mean or median, which represents the null hypothesis. In other words, if the sample value is very similar to the hypothesised value, there is likely to be no significant difference.",
					"Independent measurements mean that something (a person, measurement or group) is not systematically related to something else (another person, measurement or group). In statistics this generally refers to an answer or outcome given by any one individual in the study. So, for instance, there is no reason why one person's responses/outcomes may be more or less similar to anyone else's responses/outcomes." +
					"\n\nNon-independence may be obvious, and in fact part of the study design, if measurements are taken from paired groups or from repeated measurements of the same person/thing then the individual measurements within each pair are more associated to one another than they are to other measurements. " +
					"\n\nHowever, non-independence can be more subtle and unintentional or unavoidable; for example, if a study recruits groups of people from a number of different centres (e.g. Nurseries, GP surgeries, or schools), then the individuals coming from the same centre are likely to be more alike than individuals coming from different centres, due to shared experiences." +
					"\n\nBoth of these examples of non-independence are important features of the data and should be accounted for in the analysis of such data.",
					"Independent groups refers to the levels within a categorical/grouping variable (e.g. Gender, ethnicity, disease status, treatment group, etc.); these groups are mutually exclusive, so individuals within the study can only fall into one group. For example, disease status is a grouping variable with two independent groups or levels; a person can only ever either have the disease or not have the disease, the can never be both. " +
					"\n\nNon-independent groups or samples are referred to as paired, matched, or related samples. Non-independent measurements may come from different groups of individuals matched on a one-to-one basis into pairs according to certain similarities, or they may come from the same sample of individuals measured more than once at different times or under different conditions.",
					"An interaction means that the association between one independent variable (either a grouping variable or predictor variable) and the outcome variable is dependent on or differs according to the level of another independent variable." +
					"\n\nFor example, the effects of an anti-anxiety drug (independent variable 1) on anxiety levels (dependent/outcome variable) may differ by gender (independent variable 2), so women and men experience different outcomes of the drug. This would be a gender by drug interaction. ",
					"Inter-rater means between raters. The term inter-rater is associated with reliability analysis looking at agreement between two different people taking measurements or ratings on the same thing (and usually at the same time).",
					"It is common to refer to the individuals groups within a categorical/grouping variable as levels of that variable. So for example: blonde, red, brown, black and grey, represent five levels of a categorical hair colour variable; male and female represent the two levels of gender; and, low, medium and high represent three levels of a categorical pain threshold variable.",
					"MANOVA or Multivariate Analysis of Variance is best explained in relation to more basic ANOVA models:" +
					"\n\nThe simplest ANOVA one-way ANOVA compares numeric outcome scores (e.g. BMI) between three or more levels of a single grouping variable (e.g. Life satisfaction: comparing between people rated as low, medium, and high)." +
					"\n\nFactorial ANOVA builds on one-way ANOVA and allows analysis of more than one grouping variable at the same time. Factorial ANOVA also assessed the interactions between the different grouping variables." +
					"\n\ne.g. A study wants to examine BMI (numeric outcome variable) in terms of gender (levels: males and females) and life satisfaction (levels: low, medium, high). The study will also examine if there is an interaction between gender and life satisfaction to explain BMI (e.g. Is the association between life satisfaction and BMI different for men and women)." +
					"\n\nMultivariate ANOVA (MANOVA: multi = more than one, variate= outcome variable) builds on the examples above (that are all types of Univariate ANOVA) by allowing the analysis of more than one numeric outcome variable at the same time. The multiple outcomes will be independently and jointly analysed in terms of the grouping variables and their levels." +
					"\n\nA study wants to examine both BMI and depression together in terms of gender (levels: males and females) and level of activity (levels: low, moderate, high). The study will also examine if there is an interaction between gender and activity level BMI, depression or the combination of both.",
					"The mean is a type of average (or measure of centre/central tendency). The mean is calculated by adding together all of the individual scores and dividing the total by the number of scores." +
					"\n\ne.g. The mean of 4, 5, 10, 6, 3 and 8 is 6 "+
								"\nTotal score = 4+5+10+6+3+8 =36"+
								"\nNumber of measurement = 6"+
								"\nMean = 36/6 =6",
					"The median is a type of average (or measure of centre/central tendency). The median is the middle value of ranked measurements; what this means is you line up all of the scores in the sample in order of size and find the middle value (if you have an odd number of values) or the point between the two middle values (if you have an even number of values). There should always be the same number of data values above and below the median." +
					"\n\ne.g. The median of 4, 5, 10, 6, 3 and 8 is 5.5"+
								"\nRanked in size order = 3, 4, 5, 6, 8, 10"+
								"\nMiddle point of the six values = between the 5 and 6"+
								"\nMedian calculation = (5+6)/2  =5.5",
								"Model fit refers to how well the individual data points in a sample fit to a given model/summary of the data. The less individuals vary from the given summary estimate, the better the model fit." +
								"\n\nUsually model fit refers to regression analyses, but a very simple type of model to summarise a sample of data is the mean score (the total of all measurements divided by the number of measurements). We can compare two different samples with the same mean score (model/summary) to show examples of good and bad model fit." +
								"\n\nThe table shows two sets of data (n=8 in each), both of which have a mean of 20. However, we can see from the difference from mean values that sample 1 has values which vary a small amount above and below the mean, whilst sample 2 has values that vary greatly around the mean. So, sample 1 shows relatively good fit to the model (mean), while sample 2 shows poor fit to the model (mean)" +
								"\n\nMore complex statistical analyses that use model fit will produce values/indexes to represent model fit. This enables you to look at the goodness of fit for individual models and for comparing between alternative models.",
								"Multinomial refers to a specific type of regression analysis, which has a nominal categorical outcome variable. This means that the response options for the outcome are three or more non-ordered categories." +
								"\n\ne.g. We want to look at the variables that predict the make of car that adults buy. Make of car is a categorical outcome (e.g. Volvo, Audi, Renault, Peugeot, Aston Martin etc.) and there is no ordering to the response choices.",
								"Nominal refers to a type of categorical data in which the response options comprise of three or more non-ordered categories." +
								"\n\ne.g. Make of car is a categorical outcome (e.g. Volvo, Audi, Renault, Peugeot, Aston Martin etc.) and there is no ordering to the response choices. Similarly, ethnicity, degree subject, favourite colour, etc., are all categorical variables with more than two possible response options that have no specific ordering.",
								"There are two major branches of analyses in statistical inferential testing: parametric and nonparametric tests." +
								"\n\nNonparametric statistical tests make no specific assumptions about the data being analysed. Nonparametric tests work on the ranks (ordering) of values in the data, rather than the raw data themselves, meaning they are robust but are not very sensitive/precise. " +
								"\n\nThe opposing branch of tests, the parametric tests, are more precise and make greater use of the data, but require numeric data to be normally distributed, a minimum of 20 cases, and approximately equal variability in the data, for each group being analysed, and in categorical data proportions in each group should not be extreme. These are known as parametric assumptions. " +
								"\n\nNonparametric tests do not require any of these things to be true, so if data do not meet parametric assumptions, the nonparametric tests are more valid.",
								"Numeric means something that is measured and recorded on a number scale. " +
								"\n\nNumeric data can be subdivided into discrete numeric, which means only whole numbers or integers can be taken (e.g. Number of siblings, number of admissions to hospital, or number of ducks on a pond), and continuous numeric, which means any value can be taken including decimal, positive and negative values (e.g. Height, weight, age, temperature).",

								"Observed data is the information that is actually measured and recorded about individuals in a study.",
								"One-to-one or individual matching is used to minimise the difference between groups when two separate/independent groups are compared in analysis (e.g. A diseased group and a control group). One-to-one matching means that for every individual recruited into one group, a person with similar characteristics is intentionally recruited into the other group. " +
								"\n\nMatched groups is not the same as matched pairs, and data should only be analysed as paired if one-to-one matching has been undertaken.",
								"The simplest ANOVA one-way ANOVA compares numeric outcome scores (e.g. BMI) between three or more levels of a single grouping variable (e.g. Life satisfaction: comparing between people rated as low, medium, and high",
								"Ordinal refers to a type of categorical data in which the response options comprise of three or more ordered categories." +
								"\n\ne.g. Satisfaction rating is a categorical variable when levels such as low, medium, and high have a clear and universal ordering. Similarly, weight status (underweight, normal weight, overweight and obese), pain rating (low, moderate, high), likerts scales (e.g. Strongly disagree, disagree, neither, agree, or strongly agree), and disease progression (stage I, stage II, stage III) are all other examples of categorical variables with obviously ordered response options.",
								"The outcome is the main variable of interest; it is the variable that we measure in all cases within a sample and examine how the variable differs between groups or according to other factors (e.g. How does the outcome change in response to a treatment or intervention). " +
								"\n\ne.g. In a study looking at different treatments for high cholesterol, cholesterol level is the outcome variable. Similarly if we want to know the effects of learning contacts hours on exam results, the exam results are the outcome variable." +
								"\n\nSometimes the outcome variable is referred to as the dependent variable we are looking at how the outcome changes depending on other factors.",
								"Outliers are people or cases within a sample that score very differently to the majority of other people/cases in that sample. Outliers that sit particularly far away from the rest of the cases are sometimes referred to as extreme values." +
								"\n\nOutliers can affect the distribution of data and can also affect the validity of summary measurements including the mean and standard deviation. Each outlier should be considered individual and removed if it is an error value (e.g. Data inputting errors or impossible values for the given variable). However, outliers are not necessarily false/error measurements, so they should not just be removed; removing outlier that are valid measurements can also damage the validity of study results. " +
								"\n\nAnalyses should be run with and without outlying individuals/measurements and the results of both should be compared and reported to show the influence of the outliers.",
								"Pairing or paired-samples means that individuals or cases within a study have been matched on a one-to-one basis, according to certain pre-specified characteristics. Pairing removes the influence from those characteristics on results and means that the individuals in each pair are not independent of one another (i.e. They have intentional systematic similarities)." +
								"\n\nPairing or paired-samples can also refer to multiple measurements taken from the same sample of individuals (this may also be referred to as related or repeated measures). Taking measurements from the same sample under different conditions (as opposed to measuring two separate groups under different conditions) eliminates the influence of individual differences that might confound results.",
								"The paired-samples t-test is a parametric inferential statistical test. It is used to assess whether the mean difference between paired individuals/related measures differs significantly from zero (the null hypothesis than there is no within-pair difference).",
								"There are two major branches of analyses in statistical inference testing: parametric and nonparametric tests." +
								"\n\nParametric tests make the best use of all of the data in a sample and so can be more precise in their results. However, in order for the results of parametric tests to be valid/true certain criteria must be met: numeric data should be approximately normally distributed in each group to be analysed, there should be a minimum of 20 cases/people in each group, and there should be approximately equal variability in the data for each group. When analysing categorical data, the proportions of the sample in each group should not be extreme (>90% or <10). These are known as parametric assumptions. " +
								"\n\nNonparametric tests do not require any of these things to be true, as they use the ranks (ordering) of data rather than the raw data themselves. This means that these tests are less sensitive than parametric tests but more robust, so if data do not meet parametric assumptions, the nonparametric tests are more valid.",
								"A percentage refers to the number of people/cases in one group, divided by the total number, multiplied by 100 (the value obtained before multiplying by 100 is the proportion). This might be the number of people in one group divided by the total number of people in the sample, multiplied by 100, or the number of events in one condition divided by the total number of events, multiplied by 100." +
								"\n\ne.g. If there are 350 people in a total sample and of the 350, 189 were female and the other 161 were male, the percentage of females in the sample is 54% (189/350)*100.",
								"A Predictor variable is used to explain (or predict) differences in an outcome variable. The term predictor variable is most commonly applied to analyses that uses models of multiple variables to explain changes in an outcome (e.g. Regression, ANOVA), and is synonymous to explanatory variable, independent variable, or covariate.",
								"A proportion refers to the number of people/cases in one group, divided by the total number (if the resulting value is then multiplied by 100, this is the percentage). " +
								"\n\nThis might be the number of people in one group divided by the total number of people in the sample, or the number of events in one condition divided by the total number of events." +
								"\n\ne.g. If there are 350 people in a total sample and of the 350, 189 were female and the other 161 were male, the percentage of females in the sample is a proportion of 0.54.",
								"Ranking involves arranging all of the values in a sample of data in order of magnitude (from smallest to largest). The values are then numbered in their new order to give the ranks. The number of ranks should always be equal to the number of values in the sample." +
								"\n\ne.g. The 12 data points below range from 5-49 but will occupy 12 ranks. If there are multiples of the same values in the data, there is no way to order them, so giving them different ranks is not appropriate (since different ranks imply a different value); therefore, duplicate values should be given an equal share of the combined ranks. " +
								"\n\ne.g. The 12 points below range from 5-49, and will still occupy the ranks 1-12, but this time duplicate values are included in the data." +
								"\n\nThe two instances of 11 above cannot have the different ranks of 2 and 3 because they are the same size; therefore, they get an equal share of the total rank value of 5 ((2+3)/2). Similarly, instead of ranking the three 36s as 8, 9 and 10, they all get 9, because this is an equal share of 27 ((8+9+10)/3)." +
								"\n\nRanking is used in nonparametric tests, which analyse the position/rank of values in the list rather than the distribution of the raw values themselves.",
								"A rater refers to a person making measurements, ratings, judgements or diagnoses.",
								"Regression is a powerful and flexible method for statistical analysis. Regression analysis is used when you have a particular outcome of interest and you want to assess the associations between this outcome and one or more predictor variables. A regression model with one outcome and one predictor is a simple regression; if two or more predictor variables are entered into the regression it is a multiple or multivariable regression." +
								"\n\nThere are many different types of regression analysis, and the appropriate type to choose is determined by the nature of the outcome variable. The most common regression type is linear regression; this is used when the outcome variable is continuous numeric. Other common types noted in this app are binary logistic (binary categorical outcome), ordinal logistic (ordinal categorical outcome), poisson (frequency numeric outcome), cox proportional hazards (time-to-event outcome), and multinomial logistic (nominal categorical outcome) regressions." +
								"\n\nThe predictor variables form a model to explain variability in the outcome. A good regression model is a set of predictor variables that explain a significant amount of this variability. A model can be used to make predictions about other values of the outcome within the range of, but not necessarily observed in, the data. " +
								"\n\nPredictor variables relevant to the research question and potential confounding variables should be entered into the regression model." +
								"\n\nFor example, imagine you wanted to assess the relationship between lifestyle variables (e.g., number of takeaways per week, number of minutes exercise per day, mode of transport to work, ect.) and weight in adulthood. Weight would be the outcome and lifestyle variables would be the main predictors/covariates, however, you would likely also add other variables such as age, height and gender into the model to account for their influence on weight." +
								"\n\nIf relevant, regression analysis can also be used to model more than one outcome variable; this is called multivariate regression (multivariate should not be confused with multiple or multivariable, which refer to several predictor variables).",
								"A regression model summarises the relationship between an outcome variable and one or more predictor/explanatory variables. In its simplest form, one numeric outcome and one numeric predictor, the model refers to the line that is fitted to the data.",
								"Reliability refers to the stability, repeatability, or consistency of measurements of the same thing over time, condition, or rater. Specifically, how comparable and dependable are measurements of the same thing from one condition to another." +
								"\n\nA rater or tool with good reliability will give the same result/rating on any occasion of measurement." +
								"\n\nThere are numerous types of reliability, but the main types focus on either intra-rater reliability (does a rater or measurement tool consistently measure in the same way over time and/or condition) or inter-rater reliability (do different raters or different measurement tools make consistent measurements of the same thing)",
								"Repeatability is another term for reliability or consistency of measurements of the same thing over time, condition, or rater. Specifically, how comparable and dependable are measurements of the same thing from one condition to another." +
								"\n\nA rater or tool with good repeatability will give the same result/rating on any occasion of measurement." +
								"\n\nThe main types of reliability/repeatability are intra-rater (does a rater or measurement tool consistently measure in the same way over time and/or condition) and inter-rater (do different raters or different measurement tools make consistent measurements of the same thing)",
								"Repeated measures means that more than one measurement of the same thing (outcome variable) is taken at different times or under different conditions." +
								"\n\ne.g. 1, Cholesterol levels (outcome variable) may be measured before treatment, immediately after treatment, and at monthly follow-ups. The thing being measured (cholesterol) is always the same, but the time-point changes." +
								"\n\ne.g. 2, heart rate (outcome) might be measured in the same sample of people after five different activities (sitting watching television, sprinting, skipping, cycling and swimming). The thing being measured (heart rate) is always the same but the condition changes.",
								"In most statistical analyses individual scores are summarised (e.g. Finding the mean of a sample), and the amount that each person/case differs from that summary is also of interest (e.g. With the mean we also look at the standard deviation this is known as the residual, the bit that's left over from the summary)." +
								"\n\nThe term residuals is more commonly used in Regression and ANOVA analyses, which use models to summarise data (e.g. A fitted line is used in regression). The residuals are the amounts by which each individual differs from the model." +
								"\n\ne.g. The scatterplot below shows individual data points from a sample. The regression model line is then fitted to the data. The amount that each person/point on the plot deviates/differs from the fitted line (shown with the vertical dotted lines) is that person's residual value.",
								"The sample is the people in your study. " +
								"\n\nTotal sample refers to the total number of people who took part in the study, you will see this referred to as N; so if you studied 300 people then N=300." +
								"\n\nIt is also common to refer to subgroups within the study as samples or subsamples, denoted by n; so if you study 200 people, of whom 50% are male, the male n=100." +
								"\n\nWhen undertaking sample size calculations, or deciding on appropriate analyses according to sample size, the given number refers to each group to be analysed. " +
								"\n\nFor example, if a sample size calculation indicates that you need 65 people for your study comparing lung capacity in smokers and non-smokers, this means you need at least 65 smokers and 65 non-smokers, to give a total sample of N=130." +
								"\n\nSimilarly, parametric statistical tests generally require samples of at least 20; this refers to the number of people in each group. So, if you have collected data on smoker and non-smokers to compare their lung function, you would need 20 smokers and 20 non-smokers (total N=40) to consider using parametric analyses.",
								"A significance test is the statistical method used to calculate whether or not the effect size (the size of the difference between groups or the size/strength of the association between variables) found in a study is larger than what would have occurred by chance (i.e. A genuine difference rather than no difference). " +
								"\n\nAll studies/significance tests start from a null hypothesis; the null hypothesis says that there is no effect (no difference or association) within the data and any small differences/associations will have occurred by chance. The data are then examined to see if they are consistent with the null hypothesis (little to no effect is shown) or if they are inconsistent with the null hypothesis (a large enough effect is shown that it is unlikely to be explained by chance). " +
								"\n\nA p-value is given to quantify whether or not the difference observed in the study is large enough to be considered important. A p-value gives the probability of obtaining the observed difference/effect if the null hypothesis is true (i.e. No difference or effect in the population); the smaller the p the better." +
								"\n\nIf the difference or association is big enough (i.e. The probability of it occurring by chance is very small) we call this a statistically significant result.",
								"All studies start with a null hypothesis; the null hypothesis says that there is no effect (no difference or association) within the data and any small differences/associations will have occurred by chance. The data are then examined to see if they are consistent with the null hypothesis (little to no effect is shown) or if they are inconsistent with the null hypothesis (a large enough effect is shown that it is unlikely to be explained by chance). " +
								"\n\nA p-value is given to quantify whether or not the difference observed in the study is large enough to be considered important. A p-value gives the probability of obtaining the observed difference/effect if the null hypothesis is true (i.e. No difference or effect in the population); the smaller the p the better." +
								"\n\nA result (the difference or association) is referred to as statistically significant if the probability of it occurring if the null hypothesis is true is very small.",
								"Spread or measures of spread are types of summary/descriptive statistics that refer to the variability between people/cases in a sample of data  they summarise how spread out they are from each other. The two common measures of spread are standard deviation (the measure of spread that goes alongside the mean), and interquartile range (the measure of spread that goes alongside the median).",
								"Study design refers to the research question, who/what data will be collected from, what variables will be collected, and how data will be analysed to try and answer the research question. " +
								"\n\nWho/what data will be collected from: who/what participants will be recruited, how many, where from, will they be randomised, will groups be paired or independent, will measurements be repeated or independent." +
								"\n\nWhat variables will be collected: how many variables, numeric, categorical, confounding factors" +
								"\n\nHow data will be analysed: parametric tests, nonparametric test, paired analyses ",
								"A contingency table is constructed to show the relationship between two categorical variables by showing how many people are in each group of one categorical variable contingent on the groups of the other categorical variable.",
								"Test-retest means between tests. The term test-retest is associated with reliability analysis looking at agreement between two different measurements or ratings on the same thing, taken by the same rater and usually with a time interval between the two (or more) measurements/ratings.",
								"Time-to-event literally means the amount of time that elapses before an event occurs for an individual or before the individual is no longer followed in the study" +
								"\n\nTime-to-event data is used in survival analysis; in survival analysis individuals or cases are followed for different amounts of time (because they enter and exit the study at different times), and during that time the event of interest either occurs or does not occur. ",
								"Total agreement refers to the proportion or percentage of measurements where two raters give the same response, regardless of what the response is." ,
                                "The one-sample t-test is a parametric inferential statistical test. It is used to assess whether a sample mean is significantly different from a pre-specified or hypothesised value (typically this comparison value should be obtained from literature or expertise). ",
                                "The two-sample t-test is a parametric inferential statistical test. It is used to assess whether two sample means differ significantly from one another.",
								"Variability refers to how much individuals within a sample differ or vary from one another, and from the average. The most common measure of variability is standard deviation (or variance) which tells you the average amount that each person in the sample differs from the mean score. If the median is used as the average, then the appropriate equivalent/alternative to the standard deviation is the interquartile range (this tells you the range of the middle 50% of people/cases in the sample, chopping off the top and bottom quarters).",
								"Variables are the pieces of information (the data) that are collected on each person/case in a study. The main distinction between different variables is between numeric (measured on a number scale) and categorical (groups/options) data. Understanding this distinction is essential for choosing and conducting appropriate analyses." +
								"\n\ne.g. Height, age, weight, gender, number of siblings, annual income, socioeconomic status, heart rate, customer satisfaction, depression level, eye colour, etc.",
								"Within the test included in this app, weighted, weights or weighting are relevant to weighted kappa. This is the test of agreement between two categorical measurements when there are more than two ordered response categories. Standard kappa is based on binary responses (e.g. Yes/No) and so only absolute agreement or disagreement is possible; but, when there are several ordered responses there are different levels of disagreement." +
								"\n\nComplete agreement (on the negative table diagonal) will receive a weighting of 1; then, the greater the difference between the two ratings, the smaller the proportion of agreement it gets (i.e. The smaller the weight), down to maximum disagreement which is given a weight of 0."

					

	}
					;
	
	protected void onCreate(Bundle savedInstanceState) 
	{
		super.onCreate(savedInstanceState);
	    this.requestWindowFeature(Window.FEATURE_NO_TITLE);
	    setContentView(R.layout.glossary);
	    
	    ImageView backButton = (ImageView)findViewById(R.id.backButton);
        backButton.setOnClickListener(new View.OnClickListener()
        {
        	@Override
        	public void onClick(View view)
        	{

        		finish();
        	}
        });
	    
	    listView = (ListView)findViewById(R.id.listView1);
	    listView.setOnItemClickListener(onClick);
	    adapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, definitions);
	    listView.setAdapter(adapter);
	}
	
	ListView.OnItemClickListener onClick = new ListView.OnItemClickListener() 
	{
		  @Override
		  public void onItemClick(AdapterView<?> list, View view, int item, long id)
		  {
			  Intent intent = new Intent(GlossaryActivity.this, InformationActivity.class);
		      intent.putExtra("Explanation", data[item]);
		      intent.putExtra("Title", definitions[item]);
		      intent.putExtra("GlossaryActive", "false");
		      startActivity(intent);
		  }
	};    
}
